### ISSUE TITLE
Automatically add "part stock" quantities to InvenTree when importing parts

### ISSUE THREAD

**Issue by ndbroadbent** [sparkmicro/Ki-nTree#102]
Thanks for building this awesome tool! I was just wondering if there is a way to automatically add part stock as well? I'm trying to import lots of electronic components in my workshop, and it's a bit tedious that I have to create new stock items for every part. It would be useful if there was another field where I could choose the number of parts that I have and the stock location, and it creates the part stock entries with all these fields filled out: Supplier Part, Stock Location, and Quantity.

Is there already an option for this? If not, would you accept a PR?

**Comment by eeintech** [comment]
Hi @ndbroadbent

Sorry for the late answer, been busy lately...

With InvenTree's Python API it is very easy to update the stock of all your parts at once, you could:
1. Create a spreadsheet with the supplier part, stock location and quantity
2. Write a script that takes the spreadsheet as input and updates InvenTree with API calls

I'm intentionally limiting the features of Ki-nTree to *just* setting up parts in both KiCad and InvenTree, I would not like this tool to become too complicated. Sorry if that's not the answer you wanted, hope the option described above works for you.
