### ISSUE TITLE
Any suggestions for keeping track of a large number of 1/4W resistors from a resistor pack?

### ISSUE THREAD

**Issue by ndbroadbent** [sparkmicro/Ki-nTree#103]
I've bought a few packs of through-hole 1/4W resistors for breadboarding and prototyping (eg. 1.8K, 2.0K, 2.2K) I would like to start organizing and keeping track of these.

There's a large number of different values and lots of different DigiKey products to import, so I definitely want to find a way to automate this and do a big batch import. For example, [all of the results for this query](https://www.digikey.co.nz/en/products/filter/through-hole-resistors/53?s=N4IgjCBcoExaBjKAzAhgGwM4FMA0IB7KAbXADYBWAFgGYQBdfABwBcoQBlFgJwEsA7AOYgAvvjrQQSSGix5CJEDAoAGOoxCt2XPkNH4wAdirwpKDDnxFIpGjEp2GzNpE48BwsSAC0ESdNlLBRsQKioATgh6ES84EO5sTF5MFgJuEHwAJQApABUAIScQClMmKDBmMshlLzJTXgATdhgVAA4S53YAVX5eFgB5ZABZbFRMAFcEjJAWAE8mbHYxpBigA).

* 10: https://www.digikey.co.nz/en/products/detail/lumimax-optoelectronic-technology/CF1-4W10RJTB/16710451
* 180: https://www.digikey.co.nz/en/products/detail/lumimax-optoelectronic-technology/CF1-4W180RJTB/16708329
* 270: https://www.digikey.co.nz/en/products/detail/lumimax-optoelectronic-technology/CF1-4W270RJTB/16708376
* 1K: https://www.digikey.co.nz/en/products/detail/lumimax-optoelectronic-technology/CF1-4W1KJTB/16708299
* 2K: https://www.digikey.co.nz/en/products/detail/lumimax-optoelectronic-technology/CF1-4W2K7JTB/16708187

Do you have any suggestions for how to automate this? Is there an example script I can use to generate [CSV or XLSX that can be imported into InvenTree](https://inventree.readthedocs.io/en/stable/settings/import/)?

**Comment by eeintech** [comment]
Hi @ndbroadbent 

Once again I think what you are looking for is putting the [InvenTree's Python API](https://inventree.readthedocs.io/en/latest/api/python/python/) to use :smiley: 

The repository is located here.

I'm sure you can find a lot of examples for that, also look into https://github.com/sparkmicro/Ki-nTree/blob/main/kintree/database/inventree_api.py where I wrote a lot of wrapper functions using the Python API.
