### ISSUE TITLE
LCSC  Warning: API data download failed

### ISSUE THREAD

**Issue by PricelessToolkit** [sparkmicro/Ki-nTree#106]
Hi, First of all, I want to say a huge thank you for this great tool!
I think after today's LCSC update "shop in maintenance mode 5+ hours"  Ki-nTree cant fetch data. 
I have tried several parts numbers C2935912, C383211, C2907011 .

the terminal gives the following errors

[MAIN]  LCSC search for C2907011
[INFO]  Warning: API data download failed (HTTP Error)
[INFO]  Error: Failed to fetch data for "C2907011"

Maybe they changed something?

**Comment by PricelessToolkit** [comment]
ok, Thanks!

**Comment by PricelessToolkit** [comment]
> Related I think: https://blog.honzamrazek.cz/2022/12/jlcparts-falling-down-to-ashes/
> 
> So it seems like JLC PCB and LCSC discontinued access to their API... I have sent a message to LCSC via their website, let's see if I get a response...

Yesterday I sent a message too

**Comment by eeintech** [comment]
I am not really sure either why cutting legs on everybody would be a good idea, without instating a new option.

I have responded to their message above and they said: "We will provide API access to our long-term cooperation customers" and then asked for my account email address to keep me posted.
Not sure where this is going to lead...

**Comment by PricelessToolkit** [comment]
if it's not difficult, let me know if there is news. Thanks

**Comment by PricelessToolkit** [comment]
After changing the URL everything works again.
Thanks

**Comment by eeintech** [comment]
@PricelessToolkit Check out the [`0.6.3` release](https://github.com/sparkmicro/Ki-nTree/releases/tag/0.6.3)
