### ISSUE TITLE
Error on startup after clean install

### ISSUE THREAD

**Issue by Fotte** [sparkmicro/Ki-nTree#112]
Hey guys.

I just wanted to try Ki-nTree out and fired up a fresh xubuntu 20.04.1 VM. My problem is I can not start kintree.

kintree Version: 0.6.4
Python Version: 3.10.6
Installed via pip using virtual environment.

Error on startup:
`
(env-kintree) f@f-virtual-machine:~$ kintree
[ERROR] some Ki-nTree configuration files seem to be missing
`

I did not change the config files (nor did I copy a basic set). Am I supposed to do that before the first startup? I could not find it in the documentation :(

**Comment by eeintech** [comment]
Hello @Fotte 

This is my bad! I introduced a bug in the latest release (`0.6.4`) which I will fix in `0.6.5`, I'll keep you posted when released!

**Comment by eeintech** [comment]
`0.6.5` is now on PyPI, let me know if it works on your machine now :+1:

**Comment by Fotte** [comment]
Hi @eeintech
Thanks for your reply. The updated version works. I still had to manually install python3-tk - this is probably obvious for python people?

Anyway: kintree starts up now. Thank you for your effort!

**Comment by eeintech** [comment]
I'm gonna take a guess here as I don't know xubuntu but I imagine Python 3.10 is not their default/supported version and you have probably installed it yourself, which in this case was probably the reason why you were missing Tkinter packages. In supported versions this shouldn't be needed, which is the case for most people.
