### ISSUE TITLE
Part already in Inventree database, different MPN

### ISSUE THREAD

**Issue by martin323232** [sparkmicro/Ki-nTree#113]
For some components with different MPN and even some with different manufactuerer I get "part already in Inventree database"

GR67M20A and GR67M25A gets added to the same part in inventree.

![image](https://user-images.githubusercontent.com/6439801/210723968-17e4fe77-b926-4296-b483-4cb35cb37d37.png)

**Comment by martin323232** [comment]
Had to add a different name for the two grommets.

**Comment by eeintech** [comment]
Hi there @martin323232 

Here the problems is that those two parts can be differentiated as their name and description are the same on Digi-Key... and InvenTree does not accept a new part when those are the same.
The only way you can create a new part is to change the name, for instance for `GR67M20A`, you can append the MPN at the end of the name:
![image](https://user-images.githubusercontent.com/4020546/210840021-49c832ea-9d54-4143-bb6f-a52d94030561.png)

Before you do that, I just found a bug with that that I am going to fix in `0.6.5`, give me a bit of time to release it, I'll let you know :smiley: 

> even some with different manufactuerer

If an InvenTree part already contains a manufacturer part with the same manufacturer **and** MPN then it will be skipped and won't be added to the database. In other cases:
- If manufacturer name is different: it will always create a **new manufacturer part** but decision to create a new InvenTree part depends if its "name" and "revision" field are the same to other existing InvenTree part
- If MPN is different: it will **always** create a new InvenTree part

**Comment by eeintech** [comment]
`0.6.5` is now on PyPI, let me know if the workaround works for you :+1:
