### ISSUE TITLE
Samacsys ComponentSearchEngine support

### ISSUE THREAD

**Issue by mikhailmihalkov** [sparkmicro/Ki-nTree#118]
Can I add support for SamacSys? ( https://componentsearchengine.com/ )

**Comment by eeintech** [comment]
Hello @mikhailmihalkov Sure, do they have an API?

**Comment by mikhailmihalkov** [comment]
I can't say for sure but there is such a plugin https://github.com/olback/library-loader There is also a bootloader application on the company's website

**Comment by mikhailmihalkov** [comment]
eeintech please clarify what questions I need to ask for development I will try to send a request

**Comment by mikhailmihalkov** [comment]
eeintech Another question) is it possible to load 3d component models through this script?

**Comment by eeintech** [comment]
> eeintech Another question) is it possible to load 3d component models through this script?

Anything is possible whenever an API is available :smiley: 

> eeintech please clarify what questions I need to ask for development I will try to send a request

You need to ask them if they have a public API available for use:
- do they accept user registration
- do they provide part search endpoint
- etc.

**Comment by eeintech** [comment]
@mikhailmihalkov I just contacted them using their contact form: https://componentsearchengine.com/contact-us
If they don't respond in few days, I'll try their email address: info@SamacSys.com

**Comment by eeintech** [comment]
FYI- Email sent, with little hope to get a response :confused:

**Comment by mikhailmihalkov** [comment]
I have access to their plugins for different programs look maybe there is a hint there....
[LibraryLoaderSetup2v50.msi.zip](https://github.com/sparkmicro/Ki-nTree/files/11010393/LibraryLoaderSetup2v50.msi.zip)

[AltiumLL2v20.zip](https://github.com/sparkmicro/Ki-nTree/files/11010394/AltiumLL2v20.zip)
[KiCad_Plugin1v40.zip](https://github.com/sparkmicro/Ki-nTree/files/11010395/KiCad_Plugin1v40.zip)
[EAGLE_Plugin2v20.zip](https://github.com/sparkmicro/Ki-nTree/files/11010396/EAGLE_Plugin2v20.zip)

**Comment by eeintech** [comment]
After multiple attempts for contact, there is no response so I will close this ticket now.

@mikhailmihalkov If you ever get more info, feel free to reach out and re-open this issue.
