### ISSUE TITLE
1.0.0b1 category does not exist

### ISSUE THREAD

**Issue by martin323232** [sparkmicro/Ki-nTree#139]
Upgraded to beta version because my usual way of adding new categories stopped working. 
After adding a new category to digikey_categories.yaml it overwritten by the program. 

Have had this issue before, but can’t remember how I fixed it. 

In beta I download all categories and after selecting the correct one it says it does not exist, have tried different categories with same result. 
Tried to take an existing part and adding and this gives "category does not exist"

![kintree](https://user-images.githubusercontent.com/6439801/225251377-85f4522a-74ea-4001-bb8d-e2c22bb749fe.JPG)

**Comment by eeintech** [comment]
Hello @martin323232 

I tried to reproduce your issue but I'm sorry I can't...

1. I added the categories to my setup:

![image](https://user-images.githubusercontent.com/4020546/225447414-2d1aea5c-a7f6-47f7-b08c-fbb1f0eb0cd2.png)

2. In InvenTree view, I clicked on "Reload InvenTree Categories" button

![image](https://user-images.githubusercontent.com/4020546/225447566-857c0890-ac7a-4fe7-94ef-9b57c16603a7.png)

3. Categories were displayed in the dropdown, I selected Thermal Pads (also added a new category code but that has nothing to do with categories)

![image](https://user-images.githubusercontent.com/4020546/225447773-a9f46b98-2872-4065-b231-1a7bb1bcbb70.png)

4. I launched the part creation in the Create view and it ran fine

![image](https://user-images.githubusercontent.com/4020546/225448145-6dfa9ef3-040e-4240-b27b-99955f8fb184.png)

Am I missing some step that you did on your end?
Can you please make sure your Ki-nTree version is `1.0.0b1` and InvenTree is `0.9.x` or later?

Thanks!

**Comment by martin323232** [comment]
It was an issue with my Inventree version, updated to 0.10.1 and got it working.
Thanks for a great addon program to Inventree and KiCad.

**Comment by eeintech** [comment]
Great to hear! Thanks @martin323232 

Closing now :smiley:
