### ISSUE TITLE
Feature request: Set initial stock level when part created

### ISSUE THREAD

**Issue by Scowt** [sparkmicro/Ki-nTree#151]
We have an existing (disorganised...) lab, with many components in boxes. 

Adding all these will be time consuming no matter what; something that could speed up the workflow would be an option to create a stock item when adding a new part via Ki-ntree.

Perhaps something like a quantity text field; if value entered, create stock item & set stock level.

**Comment by eeintech** [comment]
Should be straightforward and can be added in coming dot release

**Comment by Scowt** [comment]
I'd be happy to have a crack at it, sure

**Comment by martonmiklos** [comment]
FYA I implemented this in this branch:

https://github.com/martonmiklos/Ki-nTree/tree/add_option_to_create_stock_items

I will submit a PR after some polishing.
Feedback on the UI/implementation is welcome.
