### ISSUE TITLE
[FR] upload Datasheets to InvenTree

### ISSUE THREAD

**Issue by T0jan** [sparkmicro/Ki-nTree#162]
hi again,

I was wondering if there is any reason why there is no upload (and linking in the kicad symbol) of the datasheet(s) to the InvenTree part except from "wasn't implemented yet". Half of the way is more or less done with the local datasheets option so I think I could add the upload if there are no serious arguments against it.

Greetings.

**Comment by eeintech** [comment]
Hi @T0jan Do you mean uploading to the "Attachments" section of a part? It could be done easily yes but I never needed it myself as datasheet URL in the "Suppliers" section worked just fine.
Do you want to implement it yourself?

Thanks!

**Comment by T0jan** [comment]
@eeintech yep, the attachment section. I will implement it then together with some other minor things I have in mind.

**Comment by eeintech** [comment]
Dead datasheet is definitely a reason to store locally, but in my experience they are rare instance and can be done manually changing the URL. Anyhow, storing them in the attachment section is a great idea 😃

**Comment by T0jan** [comment]
@eeintech I ran into a problem with datasheet download which also affects the already implemented local save function: some manufactures have implemented detailed checks before you can access the download which leads to either a http error when using urllib. if you use requests instead it will download the html check page instead of the actual file.

For now I implemented a check to make sure only a intended file is uploaded but maybe you know a way to get around these check pages? searching a while in google did not yield an answer for me.

**Comment by T0jan** [comment]
implemented with #167, closing
