### ISSUE TITLE
Cannot create part in categories having slash in the name

### ISSUE THREAD

**Issue by martonmiklos** [sparkmicro/Ki-nTree#174]
I have a category in inventree:
![image](https://github.com/sparkmicro/Ki-nTree/assets/1609182/0173e8f2-67b3-484c-bff6-c76dfd4898e6)
Uploading parts fails with:
![image](https://github.com/sparkmicro/Ki-nTree/assets/1609182/d3cba6fa-642c-4881-9480-e2988df0a7dd)

**Comment by eeintech** [comment]
@martonmiklos This is a very nice use case but thanks for reporting it. I would first suggest that you switch to a dash `-` instead of a slash, I believe `DC-DC` is actually the most common used name.

**Comment by eeintech** [comment]
Unless you are attached to using slashes into categories (which is a bad idea as easily mixed-up with category tree), any chance the workaround proposed is good for you?
