### ISSUE TITLE
Testing InvenTree server from Mac M1 throws [__NSCFConstantString initialize] error

### ISSUE THREAD

**Issue by tanaes** [sparkmicro/Ki-nTree#184]
Testing Ki-nTree install on my macbook pro gave me the following erro:

```
objc[47204]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.
objc[47204]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
[TREE]	Error connecting to InvenTree server: invalid address, username or password
```

After some googlin', I came across this issue:
https://github.com/rails/rails/issues/38560

Setting `OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES` in my virtual environment fixed the problem for me.

Just FYI, in case anyone else encounters the same difficulty!

**Comment by eeintech** [comment]
Hello @tanaes, thanks for the tip!
