### ISSUE TITLE
set up : connexion with inventree not realized

### ISSUE THREAD

**Issue by gerisse** [sparkmicro/Ki-nTree#189]
Hi
first , thank you for your job about this plugin , it is great !
i have a inventree droplet digitalocean, to test different plugins : the set up didn't connect to this server. Must i install kintree plugin also in the inventree settings server ?
Kintree , actually , is installed in my home pc : must be set up on the same computer , where inventree server is installed ?
So, you, see, it's not very clear for me ! if you can clear me ...
Thanks

**Comment by eeintech** [comment]
Hello @gerisse sorry for the late response. You can install Ki-nTree on any computer, you'll have to enter the InvenTree server info into the settings menu: 

![image](https://github.com/sparkmicro/Ki-nTree/assets/4020546/547a2e4f-a863-4c0c-a8fd-5f221607795f)

Then click on the "Test" button to check the connection to the InvenTree server can be made.

Let me know if that helps and if you have any other question!

**Comment by gerisse** [comment]
Thanks but unfortunately no, like you can see :
![kintree](https://github.com/sparkmicro/Ki-nTree/assets/10636735/f5a88fbc-b4b5-42e8-8d36-eaf757468125)
i can give admin password  for this server, if you want, in PM
thanks

**Comment by T0jan** [comment]
Can you test if you can talk with the inventree demo server?

URL: https://demo.inventree.org/
username: reader
Password: readonly

**Comment by gerisse** [comment]
effectively, it s ok with demo server

**Comment by eeintech** [comment]
> effectively, it s ok with demo server

In this case it may well be the connection to your DigitalOcean server, you could source help from them or the InvenTree community!

**Comment by gerisse** [comment]
ok, thanks
