### ISSUE TITLE
Doesn't fetch prices from TME

### ISSUE THREAD

**Issue by tomse** [sparkmicro/Ki-nTree#198]
![image](https://github.com/sparkmicro/Ki-nTree/assets/1444539/83562c8e-7691-40e5-8307-4ed72753b7fb)

1.0.3 and 1.0.4 doesn't fetch prices from TME

**Comment by T0jan** [comment]
to be expected as price break handling was not implemented in these versions yet. it will be in the upcoming 1.0.5 release.

**Comment by tomse** [comment]
I've just tried v1.0.5, it seems it's still missing, or is there a bug?

![image](https://github.com/sparkmicro/Ki-nTree/assets/1444539/2420fdf4-7732-485b-821d-c12b1497ec9a)

**Comment by T0jan** [comment]
It should work, but maybe something broke. let me check with the other bug together.

**Comment by T0jan** [comment]
@tomse are you able to support me in debugging a bit? as an European I am not able to get a API-key from TME so I need someone to parse me the debug outputs etc.

**Comment by T0jan** [comment]
@tomse fixed, for now in my fork: https://github.com/T0jan/Ki-nTree/tree/tme_bugs. I will merge it here and create a new version with the fix once I added a different feature I am working on rn.

**Comment by tomse** [comment]
thanks a lot :-D

**Comment by T0jan** [comment]
@tomse should be fixed in 1.0.6. please test if it works out for you as well and then close here.

**Comment by tomse** [comment]
@T0jan thank you! both creating new part and updating existing works - awesome!!

also thank you for opening a tab with the component after adding/updating, I think that was added in 1.0.4 or 1.0.5.

**Comment by T0jan** [comment]
@tomse that was there for way longer already but you probably never noticed because something failed before Ki-nTree got there. but glad you like it :D
