### ISSUE TITLE
Incorrect supplier

### ISSUE THREAD

**Issue by Con30** [sparkmicro/Ki-nTree#205]
Digi-Key parts are failing to be created. The following message is seen when trying to create a new part: 
```
[MAIN]  Creating supplier part←[0m 
[TREE]  Creating new supplier "DIGI" 
Exception in thread Thread-149 (create_part): 
Traceback (most recent call last):
```
The Supplier Name is unchanged from what is being received from the Digi-Key API and is "Digi-Key" not "DIGI". Additionally, when the Supplier Name is manually changed to something else the same message is seen saying it is trying tp create the supplier "DIGI". Clearing the cache and reinstalling kintree does not appear to resolve the issue.

Are there any other places it could be pulling this from?

Note: This doesn't occur when using Mouser as the part supplier/API.

**Comment by T0jan** [comment]
Does this happens for specific parts or for all of them? Do you already have a supplier `Digi-Key` in your inventree database?

**Comment by Con30** [comment]
This appears to be for all parts. Yes, the supplier `Digi-Key` already exists in the database.

I'm wondering if it is searching the companies table and finding the Manufacturer `DIGI` and trying to use it as it is close to `Digi-Key`.

**Comment by eeintech** [comment]
Yup I was able to reproduce with a "DIGI" manufacturer, good catch and sorry for the issue, fixing it now...
