### ISSUE TITLE
add part on Inventree , without kicad update

### ISSUE THREAD

**Issue by gerisse** [sparkmicro/Ki-nTree#218]
Hi
To be clearest , an example : 
i bought this part  (https://www.digikey.fr/fr/products/detail/texas-instruments/SN74LS393DR/1590637) : i want add it on my inventree instance , but not really on kicad , because it 's already present in schematic std lib and in footprint lib , with SOIC14.
is it possible to do this ? not add items in kicad, only in inventree ?
Thanks.
Best regards.

**Comment by T0jan** [comment]
hi @gerisse,

yes, just make sure the kicad switch in the kicad tab is disabled before you create the part, then no kicad symbol will be generated.

![image](https://github.com/sparkmicro/Ki-nTree/assets/22519396/08556be4-1124-4f31-b3c0-56f912731732)

**Comment by gerisse** [comment]
oh, yes ! i didn't see it . Thanks!
