### ISSUE TITLE
InvenTree server field assumes https unless http specified

### ISSUE THREAD

**Issue by second-string** [sparkmicro/Ki-nTree#225]
No issue here, just adding info here in case someone else struggles with this. I was trying to connect my local Ki-nTree instance to a remote InvenTree server that's currently running without SSL certs by putting the remote URL in the Server Address field in the settings. The connection was failing with
```
[TREE]  Error connecting to InvenTree server: invalid address, username or password
```
 when it was just the url, but adding the `http://` prefix made everything play nicely.

<img width="1005" alt="Bildschirmfoto 2024-04-20 um 21 41 20" src="https://github.com/sparkmicro/Ki-nTree/assets/6549618/db3c04a2-7d91-4e93-8a33-66dabe8cc207">

**Comment by second-string** [comment]
Closing cause no issue.

**Comment by eeintech** [comment]
Good point... should add this to the doc as it may not be obvious for everybody.
