### ISSUE TITLE
LCSC supplier not working

### ISSUE THREAD

**Issue by G-Pereira** [sparkmicro/Ki-nTree#231]
The API endpoint seems to be down. Is there any new API endpoint?

**Comment by T0jan** [comment]
The old endpoint is definitely not working anymore, I was not able to find a new working one yet

**Comment by 30350n** [comment]
@zenermerps recently tracked this down and fixed it in [inventree_part_import#47](https://github.com/30350n/inventree_part_import/issues/47) and [inventree_part_import#48](https://github.com/30350n/inventree_part_import/pull/48).

It basically just changed from `https://wmsc.lcsc.com/wmsc/` to `https://wmsc.lcsc.com/ftps/wm/`.

**Comment by T0jan** [comment]
@30350n perfect, will be fixed in the next release. Until then everyone can set the API-URL in the Ki-nTree settings manually to: 

`https://wmsc.lcsc.com/ftps/wm/product/detail?productCode=`

**Comment by G-Pereira** [comment]
Thanks guys. I am so happy to continue using this tool with this fix.
