### ISSUE TITLE
LCSC link not working.

### ISSUE THREAD

**Issue by PricelessToolkit** [sparkmicro/Ki-nTree#240]
LCSC did a modification again?

Checked

https://wmsc.lcsc.com/wmsc/product/detail?productCode=C2181718

Returns

{"timestamp":"2024-06-23 03:09:47","status":404,"error":"Not Found","message":"","path":"/wmsc/product/detail"}

**Comment by T0jan** [comment]
you are still using the old API-link, please update it in your supplier settings to:

`https://wmsc.lcsc.com/ftps/wm/product/detail?productCode=`

**Comment by PricelessToolkit** [comment]
Thank you very much!!!!
