### ISSUE TITLE
Problem uploading the datasheet

### ISSUE THREAD

**Issue by simoneamadori** [sparkmicro/Ki-nTree#252]
With the last version (1.1.2), when uploading the datasheet, it will upload a file with just ".pdf" without the correct name.
And also it will be always the same file for different components.
![image](https://github.com/user-attachments/assets/92c41171-f882-4211-8935-215da8e051e1)

Thanks

**Comment by eeintech** [comment]
Sounds like a bug... @T0jan or I should investigate. Thanks for the report. Could you confirm this does not happen with `1.1.1`?

**Comment by simoneamadori** [comment]
Thanks for your great job!
I confirm that it doesn't happens in the 1.1.1.

**Comment by eeintech** [comment]
Thanks for the confirmation, it rules out the setup as a variable 👍 
It is likely my fault and I will try to fix it soon, really sorry about this!

**Comment by simoneamadori** [comment]
don't worry, is a minor trouble.
You guys are doing a great work!

**Comment by T0jan** [comment]
@eeintech something is really broken. After upgrading to 1.1.2 neither my linux nor my windows setup even tries to upload datasheets and also no images are being uploaded for me. It also gives no error messages indicating something is wrong...

I took a quick look to the changes since my last commit where I know it was still working but found no obvious errors.

**Comment by simoneamadori** [comment]
For the images, I saw that if you do an update of the part the image will be uploaded.

**Comment by T0jan** [comment]
good hint! An update of the part uploaded the image as well as the datasheet for me. We have to take a look on the differences between the part creation and update for uploads it seems.

**Comment by T0jan** [comment]
good hint, there seem to be multiple issues here, as I could confirm the behavior of the unnamed pdf after updating the part. does the PDF appears only after you updated as well or also for new parts? 

The uploaded PDF seems to be always the first one you uploaded after the update to 1.1.2 and the datasheets of no component after are being downloaded. The first datasheet is stored as `.pdf` in the cache and probably all further runs check, if this specific "file-name" is already existent in the cache and skip the download afterwards.

so the main issues are:
* no downloads or uploads happen on the initial part creation
* on part update the file naming of the PDF fails, causing all files to have no name at all

**Comment by eeintech** [comment]
Crap, sorry for the trouble and investigation... I'll do what I can to fix it soon.

**Comment by eeintech** [comment]
@simoneamadori I had broke the datasheet upload in `1.1.2`, please try `1.1.3` 😃

**Comment by simoneamadori** [comment]
Perfect, is working correctly.
Thanks for your work!
