### ISSUE TITLE
Add LCSC Supplier part link

### ISSUE THREAD

**Issue by Keybored02** [sparkmicro/Ki-nTree#264]
Currently the LCSC API doesn't provide a URL to the part when queried, unlike other vendors. So no link is passed to InvenTree when setting up the Supplier. Since it's an handy feature to have, I was looking for a workaround, and found one. Part-DB faced the same issue and used the shortURL as a Supplier Link. 
It's simply 
`private function getProductShortURL(string $product_code): string
    {
        return 'https://www.lcsc.com/product-detail/' . $product_code .'.html';
    }`
where `' . $product_code .'` is the LCSC part number.
It (should) be easy to add a `product url` to `lcsc_api.py` by building it with the `productCode` (returned by the API) and the aforementioned URL. [Source](https://github.com/Part-DB/Part-DB-server/blob/master/src/Services/InfoProviderSystem/Providers/LCSCProvider.php#L282)

**Comment by T0jan** [comment]
You are right, it's a very simple addition which was added to the next version just now.
