### ISSUE TITLE
Mouser Api doesn't work anymore?

### ISSUE THREAD

**Issue by simoneamadori** [sparkmicro/Ki-nTree#265]
In the last few days I cannot do the mouser search anymore, going to the api part and testing tells :
![image](https://github.com/user-attachments/assets/6880abd2-7e4e-47df-aee8-ca385a9dbcb2)

I've recreated the api, but the problem persists.
Any idea where I can check/control? 

They updated the API?

**Comment by simoneamadori** [comment]
Update:
if a do a search with the mouser part number I can load the data: (80-C0603C104K5RAC)
![image](https://github.com/user-attachments/assets/07a549db-19da-4e26-86b8-fd70dab2d247)
If I search with the part number C0603C104K5RAC it doesn't find it
![image](https://github.com/user-attachments/assets/e2f56a63-a68f-4a98-bf9d-6db3514f7714)

**Comment by simoneamadori** [comment]
In version 1.1.3 the mouser search works correctly search and test under supplier

**Comment by simoneamadori** [comment]
in the terminal jsut:
```
←[95m
[MAIN]  Mouser search for C0603C104K5RAC←[0m
←[91m[INFO]     Error: Failed to fetch data for "C0603C104K5RAC"←[0m
←[95m
```
I've tried also with the test code, in this case the error is also with the mouser code:
```
←[95m
[MAIN]  Mouser search for DMP2066LSN-7←[0m
←[91m[INFO]     Error: Failed to fetch data for "DMP2066LSN-7"←[0m
←[95m
[MAIN]  Mouser search for 621-DMP2066LSN-7←[0m
←[91m[INFO]     Error: Failed to fetch data for "621-DMP2066LSN-7"←[0m
```
Also tried the uninstall/install but the problem remains, there's same cache to clean up?

**Comment by T0jan** [comment]
does the connection test in the settings --> Supplier --> Mouser work?
And do you get info for any mouser part number you enter or was `80-C0603C104K5RAC` maybe just cached data?

**Comment by simoneamadori** [comment]
Doesn't work, gives error.
probably is cached data, now on few tries it gives error:
```
←[95m
[MAIN]  Mouser search for 35605R6JT←[0m
←[91m[INFO]     Error: Failed to fetch data for "35605R6JT"←[0m
←[95m
[MAIN]  Mouser search for 279-35605R6JT←[0m
←[91m[INFO]     Error: Failed to fetch data for "279-35605R6JT"←[0m
←[95m
[MAIN]  Mouser search for VS-30BQ015-M3←[0m
←[91m[INFO]     Error: Failed to fetch data for "VS-30BQ015-M3"←[0m
←[95m
[MAIN]  Mouser search for 78-VS-30BQ015-M39AT←[0m
←[91m[INFO]     Error: Failed to fetch data for "78-VS-30BQ015-M39AT"←[0m
```
If it can help I'm in italy

**Comment by T0jan** [comment]
Ok I have an idea why. 1.1.4 does not pull the newest version of the python API wrapper by default so you are probably still on the old version which can not work with 1.1.4.

to fix this run `pip install -U mouser==0.1.6` or the corresponding command to install the needed version manually. this is already fixed for the next version in the `requirements.txt`

**Comment by simoneamadori** [comment]
I've updated from 0.1.5 to 0.1.6 and that fixed it, thanks!

**Comment by eeintech** [comment]
Thanks @T0jan for the quick resolution!
