### ISSUE TITLE
Deafult Templates path not accessible 

### ISSUE THREAD

**Issue by Keybored02** [sparkmicro/Ki-nTree#266]
Hi
Couple of info first: latest kintree version, installed via pip, on a Win10 machine.

The default template path seems not directly accessible via the GUI. This means that no templates appear in the drop down menu. When trying to modify it via the settings, the browse button doesn't open a file explorer, it just briefly blinks. Modifying the source file `kicad.yaml` in the package directory or the cached file in the user directory to point to the full path of the template dir fixes the issue. Seems like the default path `kintree/kicad/templates/` might not be recognized as a valid. 

Let me know if you need further info to test whether it's a one of kind situation. Reinstalling does not affect it.

**Comment by eeintech** [comment]
Hello @Keybored02 

I reproduced your issue and, the Ki-nTree Settings view, the browsing feature seems to be broken with the default path (eg. `kintree/kicad/templates/`) present in the field:
![image](https://github.com/user-attachments/assets/290516ca-47a2-4f0b-8731-6799201c76e2)

But if you delete the entry then it works and you can pick the path to the templates:
![image](https://github.com/user-attachments/assets/f4cff2b2-68fc-4e1b-8549-ab437ce9275f)

> Note that you'll have to download the templates from this repo: https://github.com/sparkmicro/Ki-nTree/tree/main/kintree/kicad/templates

Then, back to the normal view and the list of templates should load normally:
![image](https://github.com/user-attachments/assets/bc657578-d524-4c4a-954a-8fd5b199bfd0)

Hopefully that's a good workaround for you too, probably need to fix that broken Browse behavior! 😄

**Comment by Keybored02** [comment]
Hi, thanks for the quick response! I could get it to work by modifying the .yaml file, so I'm definitely good for now. Great to know there's a quicker solution though.
