### ISSUE TITLE
Add Supplier Link field

### ISSUE THREAD

**Issue by cdwilson** [sparkmicro/Ki-nTree#34]
Now that https://github.com/inventree/InvenTree/pull/1417 has been merged and InvenTree supports ManufacturerParts, I'm wondering if you would be open to adding a separate "Supplier Link" field which uses `product_url` as the default value:

![image](https://user-images.githubusercontent.com/14631/114820866-8b135800-9d74-11eb-85c4-5b94444ec2dc.png)

This would map to the existing Supplier Link field in InvenTree:

![image](https://user-images.githubusercontent.com/14631/114821379-53f17680-9d75-11eb-8986-8252cb9aae7e.png)

The other requested change would be to change the existing Datasheet field to map to the new ManufacturerPart Link in InvenTree:

![image](https://user-images.githubusercontent.com/14631/114821244-1b519d00-9d75-11eb-81b0-ed3d8c37fe5a.png)

![image](https://user-images.githubusercontent.com/14631/114821453-72f00880-9d75-11eb-8398-f98ff242d482.png)

What do you think?

**Comment by eeintech** [comment]
I think we should fully embrace the new ManufacturerPart model and add it to Ki-nTree :smile:

**Comment by eeintech** [comment]
@cdwilson I added support for `ManufacturerPart` model, want to take a look? See #38

**Comment by cdwilson** [comment]
@eeintech just tried out the new changes, looks great, thanks for adding this!

**Comment by eeintech** [comment]
@cdwilson You're welcome! :+1:
