### ISSUE TITLE
Make the program work when your inventree instance has a self-signed cert

### ISSUE THREAD

**Issue by randrej** [sparkmicro/Ki-nTree#36]
The Python Inventree module, used here to communicate with Inventree, uses `requests` for communication. Requests  uses python-provided CA certificates by default, which means your self-signed cert won't work even if you installed it with `trust anchor <cert>.crt`. The solution is to export the env variable `REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt` before importing the inventree package, which tells `requests` to use Linux system CA certs instead. This should be done on Linux only, ignored for other platforms.

Do you agree? Shall I implement this?

**Comment by eeintech** [comment]
Oh wow I didn't think certificates could make the `requests` package barf, sorry for that!

Your proposal looks good, happy to see it implemented 😃

**Comment by randrej** [comment]
Yes, that's it. You'd have to access your Inventree instance through a reverse proxy that has SSL a self-signed cert. I'll provide a pull request.
