### ISSUE TITLE
Check hard-coded version matches Git tag before posting to PyPI

### ISSUE THREAD

**Issue by eeintech** [sparkmicro/Ki-nTree#53]
This gets me every time...

**Comment by randrej** [comment]
I can submit a PR that also changes that version in the git push action.

**Comment by randrej** [comment]
Is this the right spot?

https://github.com/sparkmicro/Ki-nTree/blob/c0d1ac3de760abe108cbabaa8109e53ab3387e73/kintree/config/settings.py#L10-L14

**Comment by eeintech** [comment]
@randrej Yes that's it, is it possible to edit the python code you think?

**Comment by randrej** [comment]
Yes, sure. I can change these 3 lines in the code directly, or we could read them from another (python/json/yaml) file if you don't like mixing generated and written code.

**Comment by eeintech** [comment]
@randrej It used to be in a YAML file but for the purpose of packaging I moved it to hard-coded inside the `settings.py`. I don't know what is the best at this point, is there maybe an easy way to hard-code a software version at the moment it is packaged using poetry?

**Comment by randrej** [comment]
There are ways to obtain the version of a local package:

https://github.com/python-poetry/poetry/issues/273

To be honest, all of this just seems complicated and inefficient: let's just generate a `__version__.py` file when we update the `pyproject.toml`. This file contains that version dict and is imported in the `settings.py` file. For local development, you can provide your own `__version__.py` - the file isn't kept in git and is included in `.gitignore`.

**Comment by eeintech** [comment]
@randrej I like this idea, do you want to implement it?
