### ISSUE TITLE
Add Arch Linux AUR package link to readme

### ISSUE THREAD

**Issue by randrej** [sparkmicro/Ki-nTree#54]
I've packaged `kintree` on Arch Linux's Arch User Repository (AUR):

https://aur.archlinux.org/packages/python-kintree/

I also packaged a couple of the dependencies in order to make it work (inventree, digikey-api, certauth, schematics), since they weren't available.

You can add a line to the readme: kintree is available on Arch Linux's AUR as `python-kintree`.

**Comment by eeintech** [comment]
Done!

https://github.com/sparkmicro/Ki-nTree#packages
