### ISSUE TITLE
License for generated parts

### ISSUE THREAD

**Issue by cdwilson** [sparkmicro/Ki-nTree#63]
Ki-nTree is licensed under the GPL-3.0 License, including the [KiCad templates](https://github.com/sparkmicro/Ki-nTree/tree/main/kintree/kicad/templates) as far as I can tell.  I'm not a lawyer, but I think this means that any symbols created from these templates also must be published under GPL-3.0 License.  

From the [GPL FAQ](https://www.gnu.org/licenses/gpl-faq.en.html#GPLOutput):
> More generally, when a program translates its input into some other form, the copyright status of the output inherits that of the input it was generated from.

I think this means that it's not possible to redistribute the generated symbols under a different license.

If this was not intentional, would you consider changing the license for the included KiCad templates and any other "inputs" so that the outputs from Ki-nTree can be redistributed under any license?

**Comment by eeintech** [comment]
Hey @cdwilson 

The reason I have set Ki-nTree under GPL3.0 license is that it uses code under that license:
https://github.com/KiCad/kicad-library-utils
https://github.com/peeter123/digikey-api

Maybe I would need to have a separate, MIT license, repository for KiCad template parts? I'd rather not...
Better yet add a provision in the license to say those templates are completely free of licenses (I made those myself)? I'm no lawyer either though, would have to look it up...
