### ISSUE TITLE
Digikey localization

### ISSUE THREAD

**Issue by Snevzor** [sparkmicro/Ki-nTree#65]
When adding a part using the Digikey API the link to the part is "digikey.com....." while I would like it to be "digikey.be...".

Is that something that could be tweaked in Ki-nTree or is this specific to Digikey.

**Comment by eeintech** [comment]
Hi @Snevzor 

Are you still interested into implementing this?

**Comment by Snevzor** [comment]
Hi @eeintech, sorry for the late response.
I briefly looked into it and it seemd feasible but then I realised that when logged in to Digikey the .com links are redirected to the local one automatically and for me that's fine for now.

**Comment by eeintech** [comment]
Cool, yes I noticed the redirects too. I'll close for now and we can re-open as needed.

**Comment by LukeARESYS** [comment]
Sorry for resuscitating an old issue, but we would like to be able to change the Digikey search locale to be able to get prices in the correct currency and correct stock availability while keeping the english language.

It would be awesome to be able to set the `x_digikey_locale_site, x_digikey_locale_language and x_digikey_locale_currency`, as stated in [this digikey_api issue](https://github.com/peeter123/digikey-api/issues/12)

**Comment by eeintech** [comment]
@LukeARESYS I reopened the issue as I wish to migrate to the new Digi-Key API too: https://github.com/peeter123/digikey-api/pull/51
