### ISSUE TITLE
Progress Bar Error

### ISSUE THREAD

**Issue by watarat** [sparkmicro/Ki-nTree#7]
Have installed Ki-nTree, (Along with functioning Inventree) and all good until near end where an error 
_"
  File "kintree_gui.py", line 804, in main
    new_part, part_pk, part_data = inventree_interface.inventree_create(part_info=part_info,
TypeError: inventree_create() got an unexpected keyword argument **'progress_window'**
"_ 
is thrown.

Looking at Python, the function call below is mismatched to the implementation, a simple change to the call made it work just fine! - Not sure which file is 'old' or 'new' so not prepared to muck with your github - maybe I just caught it mid change... 😀

 (_Parameter commented out & substituted about line 810 in kintree_gui.py)_
new_part, part_pk, part_data = inventree_interface.inventree_create(part_info=part_info,
														categories=categories,
														kicad=settings.ENABLE_KICAD,
														symbol=symbol,
														footprint=footprint,
														**_#progress_window=progressbar)_**
														**show_progress=True)**

Working now - and in total awe of functionality - thankyou so much for this!!

**Comment by eeintech** [comment]
@watarat Ohh what a bummer, I changed this argument for testing purpose and forgot to update it there, really great catch and very sorry for the trouble! I'm going to fix this immediately!

I'm glad you're enjoying Ki-nTree, thanks for the great words :smile:
