### ISSUE TITLE
Mouser image download does not work

### ISSUE THREAD

**Issue by deepthought-64** [sparkmicro/Ki-nTree#73]
When trying to import a part via Mouser, the import/download of the image fails every time.
Is there anything (besides the Mouser Part API Key) that I need to consider?

See the following log output:
```
[MAIN]  Generating Internal Part Number
[INFO]  Internal Part Number = CON-000090-00
[INFO]  Success: Added new part to InvenTree
[INFO]  Warning: Image download timed out (3s)
[INFO]  Warning: Image download timed out (3s)
[INFO]  Warning: Image download timed out (3s)
[TREE]  Warning: Failed to upload part image
```

The link to the image that is presented in the _Update Part Data_ window does work when I copy-paste it into my browser. So the data received via the API looks to be fine.
![image](https://user-images.githubusercontent.com/5528887/143912687-3d5d6c5f-2289-4a94-ba98-e355da72f034.png)

If I run the same exact part number via the Digi-Key import, the image appears just fine.

Let me know when you need more info from me. :)

**Edit:** Sorry, I should have mentioned that I only use it to create InvenTree parts. I have not used/tried the KiCAD import.

I am running  Ki-nTree from the GIT repo (most recent commit)
```
commit ef1dd4649c760b311bc58bd63687069be36df850 (HEAD -> main, tag: 0.4.8, origin/main, origin/HEAD)
Merge: ea93ccb 8fcd85c
Author: Francois <eeintech@eeinte.ch>
Date:   Fri Nov 26 15:35:37 2021 -0500
```

**Comment by eeintech** [comment]
Hello @deepthought-64 I have confirmed on my end that I can reproduce this issue, it is linked to the `requests` module failing to complete the image download while other methods (eg. wget/curl) seem to work... I will need to figure out how to fix it. In the meantime and if you are on InvenTree `0.5.x` release, you can use the handy part image URL import tool:

![image](https://user-images.githubusercontent.com/4020546/143944613-7f000855-ff5a-4b2e-bf88-b15b4e089d82.png)
(cloud icon)

![image](https://user-images.githubusercontent.com/4020546/143944663-7e1423a8-c7a7-40bb-a789-5a32eb0c874e.png)

**Comment by deepthought-64** [comment]
Hi @eeintech,

thanks for the quick response. :)

Thanks for the tip with the download tool. I am running InvenTree 0.5.4 but I had to find the option to enable this feature first. (For those looking, it is under `Settings -> InvenTree Settings -> Server -> Download from URL` or in the Admin panel it is found as `INVENTREE_DOWNLOAD_FROM_URL`)

**Comment by eeintech** [comment]
Oh yeah that's right, sorry for omitting this! I will try to fix the `requests` failure soon... thanks for the report!

**Comment by deepthought-64** [comment]
Oh, by the way, what is the difference between the way you fetch images from Digi-Key vs Mouser that prevented Ki-nTree from downloading them? (Just being curious)

**Comment by eeintech** [comment]
@deepthought-64 It's exactly the same method but Mouser is more reluctant to give the image away? It used to work so maybe they've added extra blocking feature to prevent bots scrapping their pages or something like that maybe 😕

**Comment by deepthought-64** [comment]
Yeah, I have noticed that the image URL download tool is also not able to fetch the images from Mouser. Maybe they are filtering by User-Agent?
