### ISSUE TITLE
Documentation Addition

### ISSUE THREAD

**Issue by kontakt** [sparkmicro/Ki-nTree#82]
The minimum permissions required for a parts-creation user are as shown:
![image](https://user-images.githubusercontent.com/6045607/158088616-80f3f955-62a9-47ac-be68-e1927dac7d47.png)

I'm not sure if the View/Change perms are required.
It is good practice to limit automated tools to the bare minimum permission set they need, and I think it would be ideal to have these defined in documentation.

**Comment by eeintech** [comment]
Thanks @kontakt

You are referring to InvenTree user permission while this is the Ki-nTree repository :smiley: 
I would suggest to post here for a proposed improvement to the documentation for third-party tools permissions:
https://github.com/inventree/inventree-docs/issues

**Comment by kontakt** [comment]
That is one way to approach that, but it can also be approached by showing which permissions Ki-nTree requires to function.

**Comment by eeintech** [comment]
Well good point, I could have a note about this :smiley:
