### ISSUE TITLE
Can't get LCSC parts

### ISSUE THREAD

**Issue by sfabris** [sparkmicro/Ki-nTree#83]
Hello,
I can't get any LCSC part. Error is too generic, so I tried to debug:

 @timeout(dec_timeout=30)
    def search_timeout():
        url = 'https://wwwapi.lcsc.com/v1/products/detail?product_code=' + part_number
        response = requests.get(url)
        return response.json()

The request.get(url) is hitting a 404 :-(, however if paste the same url string in a browser I can get the full page.

Maybe they don't like anymore our user agent?

Thanks for your wonderful piece of software

**Comment by eeintech** [comment]
Hi @sfabris Thanks for the bug report!

Yes I'm able to reproduce... will fix it soon :smiley:
