### ISSUE TITLE
[Feature Request] Automatically create missing sub-category

### ISSUE THREAD

**Issue by Oakman-Dev** [sparkmicro/Ki-nTree#86]
To ease organising at component creation in Inventree, it would be beneficial to have Ki-nTree automatically create a new sub-category (or category even) if it's not found in Inventree. This would be useful for times when the existing categories does not match, and one has not been created in Inventree yet.

**Comment by eeintech** [comment]
@Oakman-Dev Please try the new release (`0.5.2`). You can enable the setting in your `~/.config/kintree/user/general.yaml` file:

```
AUTOMATIC_SUBCATEGORY_CREATE: true
```

**Comment by Oakman-Dev** [comment]
@eeintech This works flawlessly, thank you! 

> [TREE]	Warning: Subcategory "Wire-To-Board" does not exist
[TREE]	Success: Subcategory "Connectors/Wire-To-Board" was automatically added to InvenTree
