### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'pk'

### ISSUE THREAD

**Issue by KenwoodFox** [sparkmicro/Ki-nTree#90]
Installed in pipenv because the aur package depends on packages i cant seem to find, `python-inventree`?

Full traceback:

```
❯ kintree

[MAIN]  Connecting to Inventree server
[TREE]  Successfully connected to InvenTree server (ENV=TESTING)

--------------------

[MAIN]  Using Digi-Key cached data for 2616-VZH100M1CTR-0406S-ND

[MAIN]  Creating part in Inventree
[INFO]  Category: "Capacitors"
[INFO]  Subcategory: "Aluminium"
[INFO]  User Category: "Capacitors"
[INFO]  User Subcategory: "Aluminium"
[INFO]  Warning: Parameter "Temperature Coefficient" not found in supplier data
Traceback (most recent call last):
  File "/home/joe/.local/share/virtualenvs/joe-xljV_iqz/bin/kintree", line 8, in <module>
    sys.exit(main())
  File "/home/joe/.local/share/virtualenvs/joe-xljV_iqz/lib/python3.8/site-packages/kintree/kintree_gui.py", line 1164, in main
    new_part, part_pk, part_data = inventree_interface.inventree_create(part_info=part_info,
  File "/home/joe/.local/share/virtualenvs/joe-xljV_iqz/lib/python3.8/site-packages/kintree/database/inventree_interface.py", line 372, in inventree_create
    subcategory_pk = inventree_api.get_inventree_category_id(category_name=subcategory_name,
  File "/home/joe/.local/share/virtualenvs/joe-xljV_iqz/lib/python3.8/site-packages/kintree/database/inventree_api.py", line 53, in get_inventree_category_id
    cprint(f'[TREE]\t{item.getParentCategory().pk} ?= {parent_category_id}', silent=settings.HIDE_DEBUG)
AttributeError: 'NoneType' object has no attribute 'pk'
```

Not exactly sure if its an issue with just this part or others, thank you for making this software though! this should automate a lot!

**Comment by KenwoodFox** [comment]
I added a `if item.getParentCategory() is not None:` at line 49 in the above file, that got me here

![image](https://user-images.githubusercontent.com/31870999/172526694-49a89fb1-c343-46a4-beb7-29ec853c4f72.png)

Witch is odd... because

![image](https://user-images.githubusercontent.com/31870999/172526741-bab7ade2-5fa2-46e0-bb3e-5a0547c0d0d1.png)

**Comment by KenwoodFox** [comment]
![image](https://user-images.githubusercontent.com/31870999/172527125-3793ff3a-367d-4bbf-8a44-aa23eafac8d0.png)

Nope, still no go, not sure what ive done wrong

**Comment by KenwoodFox** [comment]
![image](https://user-images.githubusercontent.com/31870999/172535038-7bac78c9-84fa-4331-8f50-68d3bfd05634.png)
![image](https://user-images.githubusercontent.com/31870999/172535058-beeb88a4-124f-44e7-9e99-6aa131223c94.png)

Its not the subcatagory thats missing... its the main catagory,

**Comment by KenwoodFox** [comment]
So, what ive found is `inventree_api.get_inventree_category_id("String")` returns the correct id for any subcategory i query. But it always returns `-1` for a top level category, witch is odd because the way it looks to be setup, u need to return the id of a parent category, before querrying for a child one...

**Comment by KenwoodFox** [comment]
Woah, omg i got it working, this may be dumb but, heres what i did

```diff
diff --git a/kintree/database/inventree_api.py b/kintree/database/inventree_api.py
index 3b8517a..2ab3a7e 100644
--- a/kintree/database/inventree_api.py
+++ b/kintree/database/inventree_api.py
@@ -46,7 +46,7 @@ def get_inventree_category_id(category_name: str, parent_category_id=None) -> in
     part_categories = PartCategory.list(inventree_api)
 
     for item in part_categories:
-        if item.getParentCategory() is not None:
+        if True:
             if category_name == item.name:
                 # Check parent id match (if passed as argument)
                 match = True
```

its more of just a patch but when it dosent check for the parent being none, it can return the right id for parent and child and now it works.

**Comment by KenwoodFox** [comment]
@eeintech Im using 0.5.3

```
❯ pip freeze
...
digikey-api==0.6.1
inventree==0.7.1
kintree==0.5.3
mouser==0.1.1
```

**Comment by eeintech** [comment]
Well... no idea where that line came from 😅 Could be leftover from a much older version?

**Comment by KenwoodFox** [comment]
I couldent tell you :c i tried updating but python says 0.5.3 is the latest, so, idk, ive patched my version with my diff above, odd?
