### ISSUE TITLE
Method is_new_part returns wrong part PK when checking if there is a new manufacturer part

### ISSUE THREAD

**Issue by orlandod543** [sparkmicro/Ki-nTree#94]
- The method iterates through all the part in the list of parts
- inside the loop, when no match is found between parameters or between name and description, the method checks if there is a new manufacturer part. 
![image](https://user-images.githubusercontent.com/10001285/180947594-08559c50-51b8-43ee-b312-7e2742088036.png)

 - In the case that the MPN already exist in the database, compare is set to true and the loop breaks, returning the pk of the first element in the part_list. 
![image](https://user-images.githubusercontent.com/10001285/180948193-3e30b9fa-a980-4d0e-b943-fc8aa4e424df.png)

Expected behavior:
- The method should return the pk of the part with the matching manufacturing part number

**Comment by eeintech** [comment]
Hello @orlandod543, thanks for reporting this issue. I will take a look as soon as I can :+1:
